update

diff --git a/bin/backup-git-repos b/bin/backup-git-repos
--- a/bin/backup-git-repos
+++ b/bin/backup-git-repos
@@ -1,34 +1,40 @@
 #!/usr/bin/env bash
 
-set -eux
+set -eu
 
 hostname=$(cat /etc/hostname)
 
 repos=$(find $HOME/{git,foxglove} -not \( -path "$HOME/git/.aur/**/*" -type d -prune \) -type d -name ".git")
 
-temp_dir=$HOME/.temp-directory
+# echo $repos
+
+filter_file=$(mktemp)
 
 for dir in $repos; do
-	rm -rf $temp_dir
-	
 	cd $dir
 	cd ..
 
-	repo_name=$(basename `pwd`)
+	current_dir=$(pwd)/
+	repo_dir=${current_dir#"$HOME/"}
 
-	cp --reflink=always -r . $temp_dir
-
-	cd $temp_dir
-
-	git checkout -b $hostname
-	git add -A
-	git commit -m "Backup: $(TZ="Australia/Sydney" date)"
-	
-	current_ref=$(git rev-parse HEAD)
-
-	git remote add temp-gitea-archive git@tower.local:archive/${repo_name}.git
-
-	if [ ! $(git push temp-gitea-archive "$hostname") ]; then
-		echo "failed"
+	if [ -z "$(find . -mtime -30 -print -quit)" ]; then
+		echo "Skipping $repo_dir as no files have changed in 30 days"
+		continue
 	fi
+
+
+	git ls-files -com --ignored --directory --exclude-standard | sed "s,^,- $repo_dir," >> $filter_file || echo "failed to ls files"
+
+	echo "- $repo_dir.git/" >> $filter_file
+
+	echo "+ $repo_dir/**" >> $filter_file
+
 done
+
+echo $filter_file
+
+echo "- **" >> $filter_file
+
+cd $HOME
+
+rclone sync --transfers 16 -P "./" "tower:/files/State/$hostname/" --filter-from $filter_file
diff --git a/bin/send-to-tower b/bin/send-to-tower
--- a/bin/send-to-tower
+++ b/bin/send-to-tower
@@ -19,8 +19,9 @@ elif [ -f "$source_path" ]; then
 	# target is not a directory so just put it in the root of the inbox folder
 	target_path=""
 else
-	echo "Passed input was invalid."
-	exit 1
+	target_path=""
+	# echo "Passed input was invalid."
+	# exit 1
 fi
 
 rclone copy --transfers 16 -P "$source_path" "tower:/files/Inbox/$target_path"
