update

diff --git a/bin/bat-preview b/bin/bat-preview
--- a/bin/bat-preview
+++ b/bin/bat-preview
@@ -7,39 +7,39 @@
 # to fix that.
 
 if [ -z "$1" ]; then
-  echo "usage: $0 FILENAME[:LINENO][:IGNORED]"
-  exit 1
+	echo "usage: $0 FILENAME[:LINENO][:IGNORED]"
+	exit 1
 fi
 
-IFS=':' read -r -a INPUT <<< "$1"
+IFS=':' read -r -a INPUT <<<"$1"
 FILE=${INPUT[0]}
 CENTER=${INPUT[1]}
 
 if [[ $1 =~ ^[A-Z]:\\ ]]; then
-  FILE=$FILE:${INPUT[1]}
-  CENTER=${INPUT[2]}
+	FILE=$FILE:${INPUT[1]}
+	CENTER=${INPUT[2]}
 fi
 
 if [[ -n "$CENTER" && ! "$CENTER" =~ ^[0-9] ]]; then
-  exit 1
+	exit 1
 fi
 CENTER=${CENTER/[^0-9]*/}
 
 FILE="${FILE/#\~\//$HOME/}"
 if [ ! -r "$FILE" ]; then
-  echo "File not found ${FILE}"
-  exit 1
+	echo "File not found ${FILE}"
+	exit 1
 fi
 
 MIME=$(file --dereference --mime "$FILE")
 if [[ "$MIME" =~ binary ]]; then
-  echo "$MIME"
-  exit 0
+	echo "$MIME"
+	exit 0
 fi
 
 if [ -z "$CENTER" ]; then
-  CENTER=0
+	CENTER=0
 fi
 
 COLORTERM="truecolor" bat --style="${BAT_STYLE:-numbers}" --color=always --pager=never \
-      --highlight-line=$CENTER "$FILE"
+	--highlight-line=$CENTER "$FILE"
diff --git a/bin/sync-git-repos b/bin/sync-git-repos
--- a/bin/sync-git-repos
+++ b/bin/sync-git-repos
@@ -22,15 +22,14 @@ for dir in $repos; do
 		continue
 	fi
 
+	git ls-files -com --ignored --directory --exclude-standard | sed "s,^,- $repo_dir," >>$filter_file || echo "failed to ls files"
 
-	git ls-files -com --ignored --directory --exclude-standard | sed "s,^,- $repo_dir," >> $filter_file || echo "failed to ls files"
+	echo "- $repo_dir.git/" >>$filter_file
 
-	echo "- $repo_dir.git/" >> $filter_file
-
-	echo "+ $repo_dir**" >> $filter_file
+	echo "+ $repo_dir**" >>$filter_file
 done
 
-echo "- **" >> $filter_file
+echo "- **" >>$filter_file
 
 cd $HOME
 
